import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, ActivityIndicator, Alert } from 'react-native';
import { api, getFile, getErrorMessage } from '../../api/client';
import { Button, Card, EmptyState, ErrorState, LoadingScreen } from '../../components/ui';
import { Colors, Spacing, Radius, FontSize, FontWeight } from '../../theme';
import { RosterStudent, sortRoster } from '../../utils/studentList';
import {
  ExamRef, PdfMode, classPdfPath, studentPdfPath, filenameFromDisposition, looksLikePdf, safeFilename,
} from '../../utils/reportCards';
import { openPdf } from '../../utils/pdfFile';

// Class teacher opens a student's report card (or the whole class in one PDF) from the phone:
// the PDF is generated by the server, saved to the phone and handed to the share sheet.

interface ClassSection { sectionId: string; sectionName: string; gradeName: string; academicYearId: string }

export default function ReportCardsScreen() {
  const [sections, setSections] = useState<ClassSection[]>([]);
  const [exams, setExams] = useState<ExamRef[]>([]);
  const [sectionId, setSectionId] = useState('');
  const [examId, setExamId] = useState('');
  const [mode, setMode] = useState<PdfMode>('color');
  const [students, setStudents] = useState<RosterStudent[]>([]);
  const [initLoading, setInitLoading] = useState(true);
  const [initError, setInitError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null); // 'class' or a student id
  const requestId = useRef(0);

  const section = sections.find(s => s.sectionId === sectionId);
  const exam = exams.find(e => e.id === examId);

  const init = async () => {
    setInitLoading(true);
    setInitError(null);
    try {
      const data = await api.get<any>('/teacher-assignments/my');
      const secs: ClassSection[] = data.classTeacherSections || [];
      setSections(secs);
      if (secs.length > 0) {
        setSectionId(prev => prev || secs[0].sectionId);
        const ets = await api.get<ExamRef[]>(`/exam-types?academicYearId=${secs[0].academicYearId}`);
        setExams(ets);
        setExamId(prev => prev || ets[0]?.id || '');
      }
    } catch (err) {
      setInitError(getErrorMessage(err));
    } finally {
      setInitLoading(false);
    }
  };
  useEffect(() => { init(); }, []);

  const loadStudents = useCallback(async () => {
    if (!sectionId) return;
    const mine = ++requestId.current;
    setLoading(true);
    setError(null);
    setStudents([]);
    try {
      const data = await api.get<RosterStudent[]>(`/students?sectionId=${sectionId}`);
      if (mine === requestId.current) setStudents(Array.isArray(data) ? data : []);
    } catch (err) {
      if (mine === requestId.current) setError(getErrorMessage(err));
    } finally {
      if (mine === requestId.current) setLoading(false);
    }
  }, [sectionId]);
  useEffect(() => { loadStudents(); }, [loadStudents]);

  const sorted = useMemo(() => sortRoster(students), [students]);

  const run = async (key: string, path: string, fallbackName: string) => {
    setBusy(key);
    try {
      const { bytes, disposition } = await getFile(path);
      if (!looksLikePdf(bytes)) throw new Error('The server did not return a PDF.');
      await openPdf(bytes, filenameFromDisposition(disposition, fallbackName));
    } catch (err) {
      Alert.alert("Couldn't open the report card", getErrorMessage(err));
    } finally {
      setBusy(null);
    }
  };

  const openStudent = (s: RosterStudent) =>
    section && exam && run(s.id, studentPdfPath(exam, s.id, section.academicYearId, mode), safeFilename(`${s.name}_${exam.name}`));
  const openClass = () =>
    section && exam && run('class', classPdfPath(exam, section.sectionId, section.academicYearId, mode),
      safeFilename(`${section.gradeName}-${section.sectionName}_${exam.name}`));

  if (initLoading) return <LoadingScreen />;
  if (initError) return <ErrorState message={initError} onRetry={init} />;
  if (sections.length === 0) return <EmptyState icon="📄" message="You are not a class teacher of any section." />;

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      {sections.length > 1 && (
        <Pills items={sections.map(s => ({ id: s.sectionId, label: `${s.gradeName}-${s.sectionName}` }))} value={sectionId} onPick={setSectionId} />
      )}
      <Pills items={exams.map(e => ({ id: e.id, label: e.name }))} value={examId} onPick={setExamId} />

      <View style={styles.modeRow}>
        {(['color', 'bw'] as PdfMode[]).map(m => (
          <TouchableOpacity key={m} style={[styles.modeBtn, mode === m && styles.modeBtnActive]} onPress={() => setMode(m)}>
            <Text style={[styles.modeText, mode === m && styles.modeTextActive]}>{m === 'color' ? '🎨 Colour' : '🖨️ Black & white'}</Text>
          </TouchableOpacity>
        ))}
      </View>

      {exam && students.length > 0 && (
        <Button
          title={`Whole class — ${exam.name} (one PDF)`}
          variant="outline"
          onPress={openClass}
          loading={busy === 'class'}
          disabled={busy !== null}
          style={styles.classBtn}
        />
      )}
      <Text style={styles.hint}>Tap a student to open their report card. It opens in the share sheet — view, print, save or send it.</Text>

      {loading && <Text style={styles.muted}>Loading…</Text>}
      {error && <ErrorState message={error} onRetry={loadStudents} />}

      {exam && sorted.map(s => (
        <TouchableOpacity key={s.id} activeOpacity={0.7} disabled={busy !== null} onPress={() => openStudent(s)} accessibilityLabel={`Open report card for ${s.name}`}>
          <Card style={styles.card}>
            <View style={styles.row}>
              <View style={styles.roll}><Text style={styles.rollText}>{s.rollNo ?? '–'}</Text></View>
              <Text style={styles.name}>{s.name}</Text>
              {busy === s.id ? <ActivityIndicator size="small" color={Colors.primary} /> : <Text style={styles.open}>PDF ›</Text>}
            </View>
          </Card>
        </TouchableOpacity>
      ))}
    </ScrollView>
  );
}

function Pills({ items, value, onPick }: { items: { id: string; label: string }[]; value: string; onPick: (id: string) => void }) {
  return (
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.pillRow} style={styles.pills}>
      {items.map(i => (
        <TouchableOpacity key={i.id} style={[styles.pill, value === i.id && styles.pillActive]} onPress={() => onPick(i.id)}>
          <Text style={[styles.pillText, value === i.id && styles.pillTextActive]}>{i.label}</Text>
        </TouchableOpacity>
      ))}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.surface },
  content: { padding: Spacing.lg, paddingBottom: Spacing.xxxl },
  pills: { marginBottom: Spacing.md },
  pillRow: { gap: Spacing.sm, flexDirection: 'row' },
  pill: { paddingHorizontal: Spacing.lg, paddingVertical: Spacing.xs, borderRadius: Radius.full, backgroundColor: Colors.white, borderWidth: 1, borderColor: Colors.border },
  pillActive: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  pillText: { fontSize: FontSize.sm, color: Colors.textMuted },
  pillTextActive: { color: Colors.white, fontWeight: FontWeight.medium },
  modeRow: { flexDirection: 'row', gap: Spacing.sm, marginBottom: Spacing.md },
  modeBtn: { flex: 1, minHeight: 44, borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.border, backgroundColor: Colors.white, alignItems: 'center', justifyContent: 'center' },
  modeBtnActive: { borderColor: Colors.primary, backgroundColor: Colors.primary + '12' },
  modeText: { fontSize: FontSize.sm, color: Colors.textMuted },
  modeTextActive: { color: Colors.primary, fontWeight: FontWeight.semibold },
  classBtn: { marginBottom: Spacing.sm },
  hint: { fontSize: FontSize.xs, color: Colors.textMuted, marginBottom: Spacing.md, lineHeight: 18 },
  muted: { color: Colors.textMuted, textAlign: 'center', padding: Spacing.lg, fontSize: FontSize.sm },
  card: { marginBottom: Spacing.sm },
  row: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, minHeight: 36 },
  roll: { minWidth: 34, height: 34, borderRadius: 17, backgroundColor: Colors.primary + '14', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6 },
  rollText: { fontSize: FontSize.sm, fontWeight: FontWeight.bold, color: Colors.primary },
  name: { flex: 1, fontSize: FontSize.md, fontWeight: FontWeight.medium, color: Colors.text },
  open: { color: Colors.primary, fontWeight: FontWeight.semibold, fontSize: FontSize.sm },
});
